const actionConstant = {
    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILED: 'AUTH_FAILED',
    SIGNUP: 'SIGNUP',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    UPDATE_USER_DATA: 'UPDATE_USER_DATA',
    UPDATE_USER_DATA_INIT: 'UPDATE_USER_DATA_INIT',
    UPDATE_USER_DATA_SUCCESS: 'UPDATE_USER_DATA_SUCCESS',
    UPDATE_USER_DATA_FAIL: 'UPDATE_USER_DATA_FAIL',

    RESET_PASSWORD: 'RESET_PASSWORD',

    CHANGE_PASSWORD_INIT: 'CHANGE_PASSWORD_INIT',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAIL: 'CHANGE_PASSWORD_FAIL',

    PENDING: 'PENDING',
    PENDING_OFF: 'PENDING_OFF',

    CHANGE_FLEET_DISPLAY: 'CHANGE_FLEET_DISPLAY',
    CHANGE_RANK_DISPLAY: 'CHANGE_RANK_DISPLAY',

    STORE_POSTS: 'STORE_POSTS',
    STORE_POSTS_AND_PROFILES: 'STORE_POSTS_AND_PROFILES',

    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',

    SET_MESSAGE: 'SET_MESSAGE',
}

export default actionConstant;