const constant = {
    OFFER_OFFER_TYPE: 'offer_offerType',
    OFFER_DUTY_TYPE: 'offer_dutyType',
    OFFER_ROSTER_CODE: 'offer_rosterCode',
    OFFER_FLIGHT_CODE: 'offer_flightCode',
    OFFER_START_DATE: 'offer_startDate',
    OFFER_SIGN_ON_TIME: 'offer_signOnTime',
    OFFER_END_DATE: 'offer_endDate',
    OFFER_PLANE_TYPE: 'offer_planeType',

    REQUEST_DUTY_TYPE: 'request_dutyType',
    REQUEST_ROSTER_CODE: 'request_rosterCode',
    REQUEST_FLIGHT_CODE: 'request_flightCode',
    REQUEST_START_DATE: 'request_startDate',
    REQUEST_END_DATE: 'request_endDate',
    REQUEST_PORT_RANGE: 'request_portRange',
    REQUEST_PLANE_TYPE: 'request_planeType',

    OFFER_TYPE: 'offerType',
    DUTY_TYPE: 'dutyType',
    OFFER: 'offer',
    REQUEST: 'request',
    ROSTER_CODE: 'rosterCode',
    FLIGHT_CODE: 'flightCode',
    REGION_CODE: 'regionCode',
    START_DATE: 'startDate',
    SIGN_ON_TIME: 'signOnTime',
    END_DATE: 'endDate',
    PORT_RANGE: 'portRange',
    PLANE_TYPE: 'planeType',
    FILTER: 'filter',

    TRAINING: 'Training',
    ANY: 'Any',
    SWAP: 'Swap',
    PROFFER: 'Proffer',
    FLIGHT: 'Flight',
    REGIONS: 'Regions',
    PORTS: 'Ports',
    OTHERS: 'Others',
    SIM: 'Sim',
    GDAY: 'G Days',
    RESERVE: 'Reserve',

    A330: 'A330',
    A350: 'A350',
    AIRBUS: 'A330/A350',
    B777: 'B777',
    B747: 'B747',

    FLEET_AIRBUS: 'AIRBUS',
    FLEET_B777: 'B777',
    FLEET_B747: 'B747',
}

export default constant;